sonar.projectKey=cnkang_chatgpt-web
sonar.organization=cnkang
sonar.cpd.exclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx,**/*.property.test.ts,**/test/**/*.ts,**/test/**/*.tsx,**/test/**/*.sh
